config/routes.rb
Rails.application.routes.draw do
  resources :setlists
  resources :media
	devise_for :users
	resources :songs
	resources :authors

	authenticated :user do
		root "songs#index", as: "authenticated_root"
	end

	root "welcome#index"

end

app/models/setlist.rb
class Setlist < ActiveRecord::Base
  belongs_to :user
  has_many :songs
  has_many :medium
end

app/controllers/setlists_controller.rb
class SetlistsController < ApplicationController
  before_action :set_setlist, only: [:show, :edit, :update, :destroy]

  # GET /setlists
  # GET /setlists.json
  def index
    @setlists = Setlist.all
  end

  # GET /setlists/1
  # GET /setlists/1.json
  def show
  end

  # GET /setlists/new
  def new
    @setlist = Setlist.new
  end

  # GET /setlists/1/edit
  def edit
  end

  # POST /setlists
  # POST /setlists.json
  def create
    @setlist = Setlist.new(setlist_params)

    respond_to do |format|
      if @setlist.save
        format.html { redirect_to @setlist, notice: 'Setlist was successfully created.' }
        format.json { render :show, status: :created, location: @setlist }
      else
        format.html { render :new }
        format.json { render json: @setlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /setlists/1
  # PATCH/PUT /setlists/1.json
  def update
    respond_to do |format|
      if @setlist.update(setlist_params)
        format.html { redirect_to @setlist, notice: 'Setlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @setlist }
      else
        format.html { render :edit }
        format.json { render json: @setlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /setlists/1
  # DELETE /setlists/1.json
  def destroy
    @setlist.destroy
    respond_to do |format|
      format.html { redirect_to setlists_url, notice: 'Setlist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setlist
      @setlist = Setlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setlist_params
      params.require(:setlist).permit(:title, :date, :user_id, :song_id, :medium_id, :comments)
    end
end

app/helpers/setlists_helper.rb
module SetlistsHelper
end

app/views/setlists/_form.html.haml
.setlist-form.row
	= simple_form_for(@setlist) do |f|
		= f.error_notification
		.medium-6.columns
			= f.input :title
			= f.input :date, as: :date, html5: true
			= f.hidden_field :user, :input_html => { :value => current_user.id }, label: false, disabled: true, hidden: true
			= f.input :comments
			= f.button :submit
		.medium-6.columns
			= f.label :song_id, 'Songs'
			= f.collection_select :song_id, Song.all, :id, :title, { :multiple => true }
			= f.label :medium_id, 'Media'
			= f.collection_select :medium_id, Medium.all, :id, :title, { :multiple => true }
:javascript
	$('#setlist_song_id').multiSelect();
	$('#setlist_medium_id').multiSelect();

app/views/setlists/edit.html.haml
%h1 Edit Setlist

= render 'form'

= link_to 'Show', @setlist
= link_to 'Back', setlists_path

app/views/setlists/index.html.haml
%h1 Setlists

.setlist-list
  - @setlists.each do |setlist|
    .setlist
      %a{href: (url_for setlist)}
        #{setlist.title} ~ #{setlist.date}

= link_to 'New Setlist', new_setlist_path

app/views/setlists/new.html.haml
%h1 New Setlist

= render 'form'

= link_to 'Back', setlists_path

app/views/setlists/show.html.haml
.row
  .medium-6.columns
    %h2 #{@setlist.title}
    %h3 #{@setlist.date}
    %div= @setlist.comments
    = link_to 'Edit', edit_setlist_path(@setlist)
    = link_to 'Back', setlists_path
  .medium-6.columns
    .setlist-text
      %p list of songs and media in order somehow