config/routes.rb
Rails.application.routes.draw do
  resources :setlists
  resources :media
	devise_for :users
	resources :songs
	resources :authors

	authenticated :user do
		root "songs#index", as: "authenticated_root"
	end

	root "welcome#index"

end

app/models/author.rb
class Author < ActiveRecord::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:first_name, :last_name)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.haml
=simple_form_for @author do |f|
  = f.input :first_name
  = f.input :last_name
  = f.button :submit

app/views/authors/edit.html.haml
%h1 Editing Author

= render 'form'

= link_to 'Show', @author
= link_to 'Back', authors_path

app/views/authors/index.html.haml
%h1 Listing Authors

.author-list
  - @authors.each do |author|
    .author
      %p #{author.first_name} #{author.last_name}
      %p #{link_to 'Show', author} ~ #{link_to 'Edit', edit_author_path(author)} ~ #{link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' }}

= link_to 'New Author', new_author_path

app/views/authors/new.html.haml
%h1 New Author

= render 'form'

= link_to 'Back', authors_path

app/views/authors/show.html.haml
%h2 #{@author.first_name} #{@author.last_name}

= link_to 'Edit', edit_author_path(@author)
= link_to 'Back', authors_path