config/routes.rb
Rails.application.routes.draw do
  resources :setlists
  resources :media
	devise_for :users
	resources :songs
	resources :authors

	authenticated :user do
		root "songs#index", as: "authenticated_root"
	end

	root "welcome#index"

end

app/models/song.rb
class Song < ActiveRecord::Base
	belongs_to :setlist
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:title, :author, :text, :theme, :tempo, :key, :CCLISongNo, :scripture)
    end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.haml
.song-form.row
	= simple_form_for(@song) do |f|
		.medium-6.columns
			=f.input :title
			=f.input :author
			=f.input :theme
			.row
				.medium-6.columns
					=f.input :key, :collection => %w[A Bb B C C# Db D Eb E F F#/Gb G G# Ab Am Bbm Bm Cm C#m Dm Ebm Em Fm F#m Gm G#m]
				.medium-6.columns
					=f.label :tempo, 'Tempo'
					=f.number_field :tempo
			=f.label :CCLISongNo, 'CCLI Song Number'
			=f.number_field :CCLISongNo
			=f.button :submit
			=link_to 'Back', @song
		.medium-6.columns.song-text
			%h4 Song text
			%p Use # to denote song section, and then type text below
			=f.text_area :text

app/views/songs/edit.html.haml
%h1 Edit Song

= render 'form'

= link_to 'Show', @song
= link_to 'Back', songs_path

app/views/songs/index.html.haml
%h1 Songs

.song-list
	- @songs.order(:title).each do |song|
		.song
			%a{href: (url_for song)}
				#{song.title} ~ #{song.author}

= link_to 'New Song', new_song_path

app/views/songs/new.html.haml
%h1 New Song

= render 'form'

= link_to 'Back', songs_path

app/views/songs/show.html.haml
.row
	.medium-6.columns
		%h2 #{@song.title}
		%h3 #{@song.author}
		- if @song.theme
			%p Theme: #{@song.theme}
		- if @song.tempo
			%p Tempo: #{@song.tempo}
		- if @song.key
			%p Key: #{@song.key}
		- if @song.CCLISongNo
			%p CCLI No: #{@song.CCLISongNo}
		= link_to 'Edit', edit_song_path(@song)
		= link_to 'Back', songs_path
	.medium-6.columns
		.song-text
			= markdown(@song.text)