config/routes.rb
Rails.application.routes.draw do
  resources :setlists
  resources :media
	devise_for :users
	resources :songs
	resources :authors

	authenticated :user do
		root "songs#index", as: "authenticated_root"
	end

	root "welcome#index"

end

app/controllers/media_controller.rb
class MediaController < ApplicationController
  before_action :set_medium, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /media
  # GET /media.json
  def index
    @media = Medium.all
  end

  # GET /media/1
  # GET /media/1.json
  def show
  end

  # GET /media/new
  def new
    @medium = Medium.new
  end

  # GET /media/1/edit
  def edit
  end

  # POST /media
  # POST /media.json
  def create
    @medium = Medium.new(medium_params)

    respond_to do |format|
      if @medium.save
        format.html { redirect_to @medium, notice: 'Medium was successfully created.' }
        format.json { render :show, status: :created, location: @medium }
      else
        format.html { render :new }
        format.json { render json: @medium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /media/1
  # PATCH/PUT /media/1.json
  def update
    respond_to do |format|
      if @medium.update(medium_params)
        format.html { redirect_to @medium, notice: 'Medium was successfully updated.' }
        format.json { render :show, status: :ok, location: @medium }
      else
        format.html { render :edit }
        format.json { render json: @medium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /media/1
  # DELETE /media/1.json
  def destroy
    @medium.destroy
    respond_to do |format|
      format.html { redirect_to media_url, notice: 'Medium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medium
      @medium = Medium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medium_params
      params.require(:medium).permit(:title, :mediatype, :user_id, :url, :upload, :videoupload, :audioupload, :description)
    end
end

app/helpers/media_helper.rb
module MediaHelper
end

app/views/media/_form.html.haml
.song-form.row
	= simple_form_for(@medium) do |f|
		= f.error_notification
		- if @medium.errors.any?
			#errors
				%h2
					= pluralize(@medium.errors.count, "error")
					prevented this media from saving
				%ul
					- @medium.errors.full_messages.each do |msg|
						%li= msg
		.medium-6.columns
			= f.input :title
			= f.input :mediatype, :collection => %w[audio image youtube video], :class=>"typeSelect", :label=>'Media Type'
			= f.hidden_field :user, :input_html => { :value => current_user.id }, label: false, disabled: true, hidden: true
			= f.label :description, 'Description'
			= f.text_area :description
			= f.button :submit
		.media-form.medium-4.columns
			%div.audio-upload{:id=>'audio-upload', class: @medium.mediatype == 'audio' ? 'selected' : nil}
				= f.input :url
				= f.label :audioupload, 'or upload an audio file'
				= f.file_field :audioupload
			%div.image-upload{:id=>'image-upload', class: @medium.mediatype == 'image' ? 'selected' : nil}
				= f.input :url
				= f.label :upload, 'or upload an image'
				= f.file_field :upload
			%div.video-upload{:id=>'video-upload', class: @medium.mediatype == 'video' ? 'selected' : nil}
				= f.input :url
				= f.label :videoupload, 'Video Upload'
				= f.file_field :videoupload
			%div.youtube-upload{:id=>'youtube-upload', class: @medium.mediatype == 'youtube' ? 'selected' : nil}
				= f.input :url
		.media-preview.medium-2.show-for-medium.columns
			- if @medium.mediatype == 'image'
				- if @medium.url != ''
					= image_tag @medium.url
				- else
					= image_tag @medium.upload.url
			- if @medium.mediatype == 'video'
				= video_tag(@medium.videoupload.url, controls: true, loop: false, autoplay: true, muted: true, autobuffer: true)
			- if @medium.mediatype == 'audio'
				= audio_tag(@medium.audioupload.url, autoplay: false, controls: true)
			- if @medium.mediatype == 'youtube'
				%iframe{:allowscriptaccess => "always", :allowFullScreen => "true", :frameborder => "0", :height => "430", :src => "http://www.youtube.com/embed/#{YouTubeAddy.extract_video_id(@medium.url)}", :title => "YouTube video player", :width => "640"}

:javascript
	var selectField = document.getElementById('medium_mediatype');
	var imageDiv = document.getElementById('image-upload');
	var videoDiv = document.getElementById('video-upload');
	var audioDiv = document.getElementById('audio-upload');
	var youtubeDiv = document.getElementById('youtube-upload');

	selectField.onchange = function() {
		 if(this.value == 'image') {
			 imageDiv.style['display'] = 'block';
			 videoDiv.style['display'] = 'none';
			 audioDiv.style['display'] = 'none';
			 youtubeDiv.style['display'] = 'none';
		 }

		 if(this.value == 'video') {
			 imageDiv.style['display'] = 'none';
			 videoDiv.style['display'] = 'block';
			 audioDiv.style['display'] = 'none';
			 youtubeDiv.style['display'] = 'none';
		 }

		 if(this.value == 'youtube') {
			 imageDiv.style['display'] = 'none';
			 videoDiv.style['display'] = 'none';
			 audioDiv.style['display'] = 'none';
			 youtubeDiv.style['display'] = 'block';
		 }

		 if(this.value == 'audio') {
			 imageDiv.style['display'] = 'none';
			 videoDiv.style['display'] = 'none';
			 audioDiv.style['display'] = 'block';
			 youtubeDiv.style['display'] = 'none';
		 }

	};
</script>

app/views/media/edit.html.haml
%h1 Edit Media

= render 'form'

= link_to 'Show', @medium
= link_to 'Back', media_path

app/views/media/index.html.haml
.row
	.medium-6.columns
		%h1 Media
		- @media.each do |medium|
			.row
				.medium-6.columns
					%a{href: (url_for medium)}
						#{medium.title} ~ #{medium.mediatype}
				.medium-6.columns
					= image_tag medium.upload.thumb.url
= link_to 'Add Media', new_medium_path

app/views/media/new.html.haml
%h1 New Media

= render 'form'

= link_to 'Back', media_path

app/views/media/show.html.haml
.row
	.medium-6.columns
		%h2= @medium.title
		%p= @medium.mediatype
		%div= @medium.description
		%p #{link_to 'Edit', edit_medium_path(@medium)} ~ #{link_to 'Destroy', @medium, method: :delete, data: { confirm: 'Are you sure?' }} ~ #{link_to 'Back', media_path}
	.medium-6.columns
		-# = image_tag @medium.upload.url
		- if @medium.mediatype == 'image'
			- if @medium.url != ''
				= image_tag @medium.url
			- else
				= image_tag @medium.upload.url
		- if @medium.mediatype == 'video'
			= video_tag(@medium.videoupload.url, controls: true, loop: false, autoplay: true, muted: true, autobuffer: true)
		- if @medium.mediatype == 'audio'
			= audio_tag(@medium.audioupload.url, autoplay: false, controls: true)
		- if @medium.mediatype == 'youtube'
			%iframe{:allowscriptaccess => "always", :allowFullScreen => "true", :frameborder => "0", :height => "430", :src => "http://www.youtube.com/embed/#{YouTubeAddy.extract_video_id(@medium.url)}", :title => "YouTube video player", :width => "640"}